version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=munchmate.settings
    volumes:
      - .:/app

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: munchmate
    ports:
      - "3304:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
