USE munchmate;

-- Vegan Recipes
INSERT INTO recipes_recipe (name, recipe_type, details) VALUES
("Vegan Chana Masala", 1, "Required: Chickpeas (soaked overnight), tomatoes, onions, ginger, garlic, spices (cumin, coriander, garam masala, turmeric, chili powder), vegetable oil, cilantro. Info: A classic North Indian dish made with chickpeas in a flavorful tomato-based gravy. Cooking Steps: Sauté onions, ginger, and garlic. Add tomatoes and spices, cook until the oil separates. Add chickpeas and water, simmer until the gravy thickens. Garnish with cilantro. Time: Approximately 45 minutes (plus soaking time for chickpeas). Improvements: Add a splash of lemon juice for tanginess. You can add spinach for extra nutrients."),
("Aloo Gobi", 1, "Required: Potatoes, cauliflower, onions, tomatoes, ginger, garlic, spices (turmeric, cumin, coriander, chili powder), vegetable oil. Info: A dry vegetable dish with potatoes and cauliflower. Cooking Steps: Sauté onions, ginger, and garlic. Add tomatoes and spices, cook until the oil separates. Add potatoes and cauliflower, cook until tender. Add a bit of water if needed to prevent burning. Time: Approximately 30 minutes. Improvements: Add peas for extra sweetness. A pinch of asafoetida (hing) enhances flavor."),
("Vegetable Pulao", 1, "Required: Basmati rice, mixed vegetables (carrots, peas, beans, etc.), onions, ginger, garlic, spices (cinnamon, cardamom, cloves, bay leaves), vegetable oil. Info: A fragrant rice dish with mixed vegetables. Cooking Steps: Sauté whole spices, onions, ginger, and garlic. Add vegetables and cook for a few minutes. Add rice and water, cook until the rice is done. Time: Approximately 30 minutes. Improvements: Add cashews and raisins for richness. You can add mint leaves for a refreshing flavor."),
("Dal Tadka (Vegan Version)", 1, "Required: Yellow lentils (toor dal), tomatoes, onions, ginger, garlic, spices (cumin, mustard seeds, turmeric, chili powder), vegetable oil. Info: A simple and comforting lentil dish. Cooking Steps: Cook lentils until soft. Sauté onions, ginger, and garlic. Add tomatoes and spices, cook until the oil separates. Add the cooked lentils and simmer. Tadka (tempering): heat oil, add mustard seeds, cumin seeds, dry red chillies, and curry leaves, then pour over the dal. Time: Approximately 40 minutes. Improvements: Add spinach or other leafy greens for extra nutrients."),
("Vegetable Korma (Coconut Based)", 1, "Required: Mixed vegetables (carrots, beans, peas, potatoes), coconut milk, onions, ginger, garlic, cashews, spices (cinnamon, cardamom, cloves, coriander, cumin), vegetable oil. Info: A creamy and mildly spiced vegetable curry. Cooking Steps: Grind cashews to a paste. Sauté onions, ginger, and garlic. Add spices and vegetables, cook for a few minutes. Add coconut milk and cashew paste, simmer until the vegetables are tender. Time: Approximately 45 minutes. Improvements: Add a splash of lime juice before serving.");

-- Vegetarian Recipes
INSERT INTO recipes_recipe (name, recipe_type, details) VALUES
("Paneer Butter N", 2, "Required: Paneer, tomatoes, onions, cashews, cream, butter, ginger, garlic, spices (garam masala, chili powder, turmeric). Info: A rich and creamy paneer curry. Cooking Steps: Sauté onions, ginger, and garlic. Add tomatoes and cashew paste, cook until the oil separates. Add spices, paneer, cream, and butter, simmer. Time: Approximately 40 minutes. Improvements: Kasuri methi (dried fenugreek leaves) adds a wonderful aroma."),
("Palak Paneer", 2, "Required: Paneer, spinach, onions, ginger, garlic, cream, spices (garam masala, cumin, coriander). Info: Paneer in a creamy spinach gravy. Cooking Steps: Blanch spinach and puree it. Sauté onions, ginger, and garlic. Add spices and spinach puree, cook. Add paneer and cream, simmer. Time: Approximately 35 minutes. Improvements: Add a pinch of sugar to balance the bitterness of spinach."),
("Vegetable Biryani", 2, "Required: Basmati rice, mixed vegetables, yogurt, onions, ginger, garlic, mint leaves, coriander leaves, spices (biryani masala, saffron). Info: A flavorful layered rice dish. Cooking Steps: Marinate vegetables in yogurt and spices. Layer rice and vegetables in a pot. Cook on low heat until the rice is done. Time: Approximately 1 hour. Improvements: Caramelized onions add a sweet and savory note."),
("Malai Kofta", 2, "Required: Potatoes, paneer, cashews, raisins, cream, tomatoes, onions, ginger, garlic, spices (garam masala, cardamom). Info: Deep-fried paneer and potato dumplings in a creamy gravy. Cooking Steps: Make kofta (dumplings) and deep-fry them. Prepare the gravy and add the kofta. Add cream, and serve. Time: Approximately 1 hour. Improvements: Add saffron to the gravy for a luxurious touch."),
("Navratan Korma", 2, "Required: Mixed vegetables, paneer, nuts (cashews, almonds), cream, yogurt, onions, ginger, garlic, spices (garam masala, cardamom). Info: A rich and mildly sweet vegetable curry. Cooking Steps: Fry the nuts and paneer. Prepare the gravy with yogurt, cream, and spices. add the vegetables, nuts, and paneer, and simmer. Time: Approximately 50 minutes. Improvements: Add fruit like pineapple or apples for a sweeter korma.");